version: '3.8'
services:
  api:
    container_name: api
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DATABASE_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes: 
  data: {}
  redis:
    driver: local
 