version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DATABASE_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes: 
 data: {}