version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.16.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm run test
      - run:
          name: Run e2e Tests
          command: npm run test:e2e

  build_and_deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build App
          command: npm run build
      - run:
          name: Run Tests
          command: npm test
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_deploy
