version: 2.1
commands:
  restore-cache:
    steps:
      - restore-cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
  install-dependencies:
    steps: 
      - run: npm install
  save-cache:
    steps:
      - save-cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  generate-prisma-client:
    steps:
      - run: npx prisma generate
  generate-prisma-migrations:
    steps:
      - run: npx prisma migrate dev
  run-tests:
    steps:
      - run: npm run test:ci
      - run: npm run test:e2e
      - store_test_results:
          path: test-results
      - run: echo "export ACTIVE_BRANCH=$CIRCLE_BRANCH" >> $BASH_ENV
  greetings-from-branch:
    steps:
      - when: 
          condition: << pipeline.parameters.CIRCLE_TEST_RESULT >> != ''
          steps:
            - run: echo "No siema z brancha $ACTIVE_BRANCH"
      - when:
          condition: << pipeline.parameters.CIRCLE_TEST_RESULT >> == '' 
          steps:
            run: echo "Tests failed"

jobs:
  build-and-test:
    docker: 
      - image: cimg/node:18.16.0
        environment:
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: testUser
          POSTGRES_DB: test
          POSTGRES_PASSWORD: testPassword
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
    steps:
      - checkout
      - restore_cache
      - install-dependencies
      - save_cache
      - generate-prisma-client
      - generate prisma migrations
      - run-tests
      - greetings-from-branch
workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test
