version: 2.1
jobs:
  run_tests:
    docker:
      image: circleci/node:10
    steps: 
    - checkout
    - run:
        name: Install dependencies
        command: npm install
    - run: 
        name: Run unit tests
        command: npm run test
    -run:
        name: Run e2e tests
        command: npm run test:e2e
workflows:
  build_tests:
    jobs:
      - run_tests
