version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.16.0

jobs:
  build_and_deploy:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Unit Tests
          command: npm run test
      - run:
          name: Run e2e Tests
          command: npm run test:e2e
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_deploy
