version: 2.1
jobs:
  build_and_deploy:
    docker: 
      - image: cimg/node:18.16.0
        environment:
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: cimg/postgres
        enviroment:
          POSTGRES_USER: testUser
          POSTGRES_DB: test
          POSTGRES_PASSWORD: testPassword
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Prisma Client
          command: npx prisma generate
      - run: 
          name: Generate Prisma Migrations
          command: npx prisma migrate dev
      - run:
          name: Run Unit Tests
          command: npm run test
      - run:
          name: Run e2e Tests
          command: npm run test:e2e
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_deploy
